name: ElegantFin
previewImages:
    - image: ./preview-images/homepage.webp
      title: Homepage
    - image: ./preview-images/movies-library.webp
      title: Movies Library
    - image: ./preview-images/movie-page.webp
      title: Movie Page
    - image: ./preview-images/tv-show-page.webp
      title: TV Show Page
    - image: ./preview-images/login-page.webp
      title: Login Page
    - image: ./preview-images/settings-page.webp
      title: Settings Page
developerName: lscambo13
developerGithub: lscambo13
dateAdded: 2026-09-05
dateCreated: 2024-12-01
submittedBy: KartoffelChipss
openSource: true
license:
    name: GPL-2.0
    url: https://github.com/lscambo13/ElegantFin/blob/main/LICENSE
shortDescription: A Jellyfin theme inspired by Jellyseerr, improving the overall look and experience with various little fixes to the UI/UX.
links:
    - type: github
      url: https://github.com/lscambo13/ElegantFin
    - type: donation
      url: https://buymeacoffee.com/lscambo13
