name: Jellyfin Desktop
logo: ./logo.webp
developerName: Jellyfin Team
developerGithub: jellyfin
dateAdded: 2026-09-04
dateCreated: 2015-10-13
submittedBy: KartoffelChipss
openSource: true
shortDescription: The official desktop client for Jellyfin, built on mpv for high quality local playback.
platforms: [windows, macos, linux]
official: true
music: supported
installationLink:
    type: github
    url: 'https://github.com/jellyfin/jellyfin-desktop/releases/latest'
links:
    - type: github
      url: https://github.com/jellyfin/jellyfin-media-player
previewImages:
    - './preview-images/home.webp'
    - './preview-images/library.webp'
    - './preview-images/movie.webp'
    - './preview-images/player.webp'
features:
    hw-decode: true
    chromecast: false
