name: Pelagica
logo: ./logo.svg
banner: ./banner.svg
developerName: KartoffelChipss
developerGithub: KartoffelChipss
dateAdded: 2026-09-04
submittedBy: KartoffelChipss
openSource: true
shortDescription: A modern web, desktop and TV client for Jellyfin
platforms: [web, webos, tizen, windows, macos, linux]
mainPlatform: web
official: false
music: supported
previewImages:
    - './preview-images/home.webp'
    - './preview-images/library.webp'
    - './preview-images/series.webp'
    - './preview-images/episode.webp'
    - './preview-images/music.webp'
    - './preview-images/search.webp'
    - './preview-images/custom_sections.webp'
links:
    - type: github
      url: https://github.com/PelagicaApp/Pelagica
    - type: website
      url: https://pelagica.app
    - type: translations
      url: 'https://twoglot.com/@KartoffelChipss/pelagica'
installationInstructions:
    web: |-
        You can find a web installation instruction in [the docs](https://pelagica.app/docs/installation).
    windows: |-
        You can download an `.exe` installer from [Releases](https://github.com/PelagicaApp/Pelagica/releases/latest).
    linux: |-
        You can download a `.deb`, a `.pkg.tar.zst` (Arch Linux), or an `.AppImage` from [Releases](https://github.com/PelagicaApp/Pelagica/releases/latest).
    webos: |-
        You can find a webOS installation instruction in [the docs](https://pelagica.app/docs/webos).
    tizen: |-
        You can find a Tizen installation instruction in [the docs](https://pelagica.app/docs/tizen).
features:
    hw-decode: true
    direct-play: true
    trickplay: true
    pgs-ass-subtitles: true
    lyrics: true
    quick-connect: true
    live-tv-dvr: true
    seerr-integration: true
    kevintweaks-watchlist: true
    streamystats-recommendations: true
aiUsed: true
aiDisclaimer: I treat AI like any other tool I use. It is not a seperate "person" that can code for me or design my software. I use it for research, for finding bugs or generating small code snippets.
