name: Jellyfin for Tizen
logo: ./logo.webp
developerName: Jellyfin Team
developerGithub: jellyfin
dateAdded: 2026-09-05
dateCreated: 2019-10-12
submittedBy: KartoffelChipss
openSource: true
shortDescription: The official Jellyfin app for Samsung Tizen smart TVs, wrapping the web client for the big screen.
platforms:
    - tizen
mainPlatform: tizen
official: true
license:
    name: MPL-2.0
    url: https://github.com/jellyfin/jellyfin-tizen/blob/master/LICENSE
links:
    - type: github
      url: https://github.com/jellyfin/jellyfin-tizen
      sourcelink: true
    - type: other
      label: Samsung Smart TV App Store
      url: https://www.samsung.com/us/tvs/smart-tv/samsung-tv-apps-detail/?appId=3202007021208
features:
    quick-connect: true
    multi-server: true
